name: GitHubActionsFlutter
on: push
jobs: 
    run_push:
        runs-on: ubuntu-latest
        env:
          REPOSITORY_URL: https://github.com/santiagogarcia70/flutter_example
          IMAGE_NAME: ${{ github.repository }}/alerta-cli
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        steps:
            - uses: act10ns/slack@v1
              with:
                status: starting
                channel: '#githubactionsexample'
              if: always()
