name: Dart CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    #- name: Install dependencies
      #run: pub get
    #- name: Run tests
      #run: pub run test
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        body: Build job of ${{github.repository}} completed successfully!
        to: correopruebas7080@gmail.com
        from: santiagogarcia7080@gmail.com
        content_type: text/html
        #attachments: attachments.zip,git.diff,./dist/static/main.js
