name: GitHubActionsFlutter
on: push
jobs: 
    on-push:
        runs-on: ubuntu-latest
        env:
          REPOSITORY_URL: https://github.com/santiagogarcia70/flutter_example
          IMAGE_NAME: ${{ github.repository }}/alerta-cli
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        steps:
            - uses: act10ns/slack@v1
              with:
                status: starting
                channel: '#githubactionsexample'
              if: always()
              
            - uses: actions/checkout@v1
            - uses: actions/setup-java@v1
              with:
                  java-version: '12.x'
                
            - name: analisis de codigo estatico
              id: flutter_example
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              
            - uses: subosito/flutter-action@v1
              with:
                  flutter-version: '1.9.1+hotfix.6'
            - run: flutter pub get
            - run: flutter test
            - run: flutter build  
