name: Dart CI
#
on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - name: flutter-android-sdk
      uses: andreujuanc/flutter-android-sdk@v1.0.6
    - uses: actions/checkout@v2
    - name: flutter-cli
      uses: steebchen/flutter@v1.1.0  
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        body: Build job of ${{github.repository}} completed successfully!
        to: correopruebas7080@gmail.com
        from: santiagogarcia7080@gmail.com
        content_type: text/html
        #attachments: flutter_example/.github/workflows/dart.yml
    - name: flutter doctor sad checkout
      run: flutter doctor
    - name: print god
      run: echo "muy bien perro"
    
